name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Make Maven wrapper executable
        working-directory: ./backend/MoliceiroMeals
        run: chmod +x ./mvnw
      
      - name: Build and Test
        working-directory: ./backend/MoliceiroMeals
        run: ./mvnw test 